import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import PresentationCode from '@/components/PresentationCode'

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles['home-container']}>
        <div className={styles['home-left']}>
          <div className={styles['presentation']}>
            <div className={styles['hello-text']}>
              Hello<span style={{color: '#ed6c87'}}>.</span>
            </div>

            <div className={styles['name-text']}>
              {` I'm Jona`}<span style={{color: '#86d9f3'}}>.</span>
            </div>
          </div>

          <div className={styles['job']}>
            {`<Frontend Developer />`}
          </div>
        </div>

        <div className={styles['home-right']}>
          <PresentationCode />
        </div>
      </div>
    </>
  )
}
