export const skills = [
    {
      icon: "html",
      width: 80,
      height: 70,
      figcaption: "HTML",
    },
    {
      icon: "css",
      width: 70,
      height: 70,
      figcaption: "CSS",
    },
    {
      icon: "javascript",
      width: 120,
      height: 70,
      figcaption: "JAVASCRIPT",
    },
    {
      icon: "react",
      figcaption: "REACT",
      width: 105,
      height: 70,
    },
    {
      icon: "redux",
      figcaption: "REDUX",
      width: 70,
      height: 70,
    },
    {
      icon: "typescript",
      figcaption: "TYPESCRIPT",
      width: 70,
      height: 70,
    },
    {
      icon: "mongodb",
      figcaption: "MONGO DB",
      width: 100,
      height: 50,
      marginB: "4%",
      marginT: "10%",
    },
    {
      icon: "mongoose",
      figcaption: "MONGOOSE",
      width: 120,
      height: 70,
    },
    {
      icon: "express",
      figcaption: "EXPRESS",
      width: 110,
      height: 65,
      marginB: "5%",
      marginT: "0%",
    },
    {
      icon: "node",
      figcaption: "NODE JS",
      width: 105,
      height: 70,
    },
    {
      icon: "sql",
      figcaption: "SQL",
      width: 110,
      marginT: "14%",
    },
    {
      icon: "mysql",
      figcaption: "MYSQL",
      width: 100,
      height: 70,
    },
    {
      icon: "jest",
      figcaption: "JEST",
      width: 85,
      height: 75,
    },
    {
      icon: "next",
      figcaption: "NEXT JS",
      width: 110,
      height: 70,
    },
    {
      icon: "graphql",
      figcaption: "GRAPHQL",
      width: 70,
      height: 70,
    },
    {
      icon: "firebase",
      figcaption: "FIREBASE",
      width: 70,
      height: 70,
    },
    {
      icon: "python",
      figcaption: "PYTHON",
      width: 80,
      height: 70,
    },
    {
      icon: "git",
      figcaption: "GIT",
      height: 70,
    },
    {
      icon: "sass",
      figcaption: "SASS",
      height: 72,
    },
    {
      icon: "material-ui",
      figcaption: "MATERIAL-UI",
      width: 70,
    },
    {
      icon: "bootstrap",
      figcaption: "BOOTSTRAP",
      width: 109,
    },
    {
      icon: "react-bootstrap",
      figcaption: "REACT BOOTSTRAP",
      height: 70,
    },
    {
      icon: "styled",
      figcaption: "STYLED COMPONENTS",
      height: 70,
    },
    {
      icon: "tailwindcss",
      figcaption: "TAILWIND CSS",
      width: 155,
      height: 45,
      marginB: "3%",
      marginT: "13%",
    },
  ];
